platform :ios, '6.0'
xcodeproj 'MasterPass'

pod 'ObjectiveSugar'
pod 'KLScrollSelect', :git => 'https://github.com/DavidBenko/KLScrollSelect.git', :branch => 'No-Autoscroll'
pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'pop', '~> 1.0'
pod 'BlocksKit'
pod 'SVWebViewController', :head
pod 'SIAlertView', :git => 'https://github.com/AnyPresence-Services/SIAlertView.git', :branch => 'mc_setup'
pod 'FontAwesomeKit', '~> 2.1.0'
pod 'JMGBlockSegue'
pod 'M13Checkbox', :git => 'https://github.com/Marxon13/M13Checkbox'
pod 'BButton'
pod 'Masonry'
pod 'SwipeView'
pod 'TPKeyboardAvoiding'
pod 'BBBadgeBarButtonItem'
pod 'MBProgressHUD', '~> 0.8'